#!/bin/bash
vim -c "Stdheader" -c wq ft_isalpha.c
vim -c "Stdheader" -c wq ft_isdigit.c
vim -c "Stdheader" -c wq ft_isalnum.c
vim -c "Stdheader" -c wq ft_isascii.c
vim -c "Stdheader" -c wq ft_isprint.c
vim -c "Stdheader" -c wq ft_strlen.c
vim -c "Stdheader" -c wq ft_memset.c
vim -c "Stdheader" -c wq ft_bzero.c
vim -c "Stdheader" -c wq ft_memcpy.c
vim -c "Stdheader" -c wq ft_memmove.c
vim -c "Stdheader" -c wq ft_strlcpy.c
vim -c "Stdheader" -c wq ft_strlcat.c
vim -c "Stdheader" -c wq ft_toupper.c
vim -c "Stdheader" -c wq ft_tolower.c
vim -c "Stdheader" -c wq ft_strchr.c
vim -c "Stdheader" -c wq ft_strrchr.c
vim -c "Stdheader" -c wq ft_strncmp.c
vim -c "Stdheader" -c wq ft_memchr.c
vim -c "Stdheader" -c wq ft_memcmp.c
vim -c "Stdheader" -c wq ft_strnstr.c
vim -c "Stdheader" -c wq ft_atoi.c
vim -c "Stdheader" -c wq ft_calloc.c
vim -c "Stdheader" -c wq ft_strdup.c
vim -c "Stdheader" -c wq ft_substr.c
vim -c "Stdheader" -c wq ft_strjoin.c
vim -c "Stdheader" -c wq ft_strtrim.c
vim -c "Stdheader" -c wq ft_split.c
vim -c "Stdheader" -c wq ft_itoa.c
vim -c "Stdheader" -c wq ft_strmapi.c
vim -c "Stdheader" -c wq ft_striteri.c
vim -c "Stdheader" -c wq ft_putchar_fd.c
vim -c "Stdheader" -c wq ft_putendl_fd.c
vim -c "Stdheader" -c wq ft_putnbr_fd.c
vim -c "Stdheader" -c wq ft_lstnew.c
vim -c "Stdheader" -c wq ft_lstadd_front.c
vim -c "Stdheader" -c wq ft_lstsize.c
vim -c "Stdheader" -c wq ft_lstlast.c
vim -c "Stdheader" -c wq ft_lstadd_back.c
vim -c "Stdheader" -c wq ft_lstdelone.c
vim -c "Stdheader" -c wq ft_lstclear.c
vim -c "Stdheader" -c wq ft_lstiter.c
vim -c "Stdheader" -c wq ft_lstmap.c
